### ISSUE TITLE
vmware HCL recommends open-vm-tools

### ISSUE THREAD

**Issue by mmarseglia** [shiguredo/packer-templates#23]
the vmware hcl for centos7 recommends using the open-vm-tools bundled with the distribution.
https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=software&testConfig=16&productid=37199&releaseid=295&supRel=273,271,172,243,301,295,&deviceCategory=software&details=1&operatingSystems=202&testConfigurations=16&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc&testConfig=16

any thoughts on changing the vmware.sh script to install open-vm-tools?

**Comment by hnakamur** [comment]
Hi, @mmarseglia 
Thanks for reporting this issue.
I'm the new mainainer of this project, but I use virtualbox only, not vmware.

+1 for changing the vmware.sh script to install open-vm-tools.
However I don't know how to change it.
Could you send us a pull request for the modification to install open-vm-tools?
Thanks!

**Comment by mmarseglia** [comment]
i will, and thank you for maintaining this. it is very helpful.

**Comment by hnakamur** [comment]
I'm closing this issue since there's no update for a long time.
Feel free to reopen this issue when you have a progress.
