### ISSUE TITLE
Error building CentOS 7.1 on VirtualBox

### ISSUE THREAD

**Issue by indigo423** [shiguredo/packer-templates#28]
I tried to build the template for CentOS 7.1 and ran into the following error message:

    sudo: sorry, you must have a tty to run sudo

It seems there are others who ran in the same issue https://www.shell-tips.com/2014/09/08/sudo-sorry-you-must-have-a-tty-to-run-sudo/. I have VirtualBox 5.0.0 r101573 running and used the develop with
latest commit from

commit 33c535de36d8ccab81f689f1ccdaba0a0a0d511b
Merge: 1048d2b c46bacf
Author: Hiroaki Nakamura <hnakamur@users.noreply.github.com>
Date:   Wed Jun 24 12:02:10 2015 +0900

    Merge pull request #26 from eroad/develop

    updated ubuntu-12.04 build to use newer (12.04.5) release

**Comment by hnakamur** [comment]
@indigo423 I merged my pull request to fix the error. Thanks for your report!

**Comment by indigo423** [comment]
Works like a charm. Thank you very much!
:+1:
