### ISSUE TITLE
Build package behind proxy

### ISSUE THREAD

**Issue by SydOps** [shiguredo/packer-templates#35]
I run below commands, they runs well at beginning until the instance is started up in Virtualbox, and can't get update because no proxy setting. 

```
cd centos-6.7
packer build -only=virtualbox-iso template.json
```
I have set `http_proxy` and `https_proxy` in local pc. That's why it runs well to download iso. 

```
    virtualbox-iso: Download progress: 98%
    virtualbox-iso: Download progress: 98%
    virtualbox-iso: Download progress: 99%
==> virtualbox-iso: Starting HTTP server on port 8856
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3978)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1444259090 --memory 512
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1444259090 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.0.2)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Provisioning with shell script: scripts/base.sh
    virtualbox-iso: Loaded plugins: fastestmirror
    virtualbox-iso: Setting up Install Process
    virtualbox-iso: Determining fastest mirrors
    virtualbox-iso: Error: Cannot find a valid baseurl for repo: base
    virtualbox-iso: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock error was
    virtualbox-iso: 14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1
```
But stop at `"Couldn't resolve host 'mirrorlist.centos.org'"` when run the script `scripts/base.sh` in building image.

Are there any proxy setting I can provide to the image or in template.json? If I set proxy when building the image, will the proxy be kept in all new image, which I don't want to keep it.

**Comment by SydOps** [comment]
Seems this url gives me some hints.

**Comment by SydOps** [comment]
I can add proxy setting in each `script/*.sh` files and fix this issue. 
```
export http_proxy=http://host:port
export https_proxy=http://host:port
```
But I don't like this way, any suggestions?

**Comment by hnakamur** [comment]
How about using variables in Packer templates?
[User Variables in Templates - Packer by HashiCorp](https://www.packer.io/docs/templates/user-variables.html)

**Comment by SydOps** [comment]
Thanks for the links, but the variables are not for proxy setting to use in script running in the build image.

**Comment by hnakamur** [comment]
I see an example https://groups.google.com/forum/#!topic/packer-tool/l8-R4L5Z4fQ
using both `variables` and `environment_vars`.

First it sets packer variables with values of environment variables,
Then it sets environment variables with packer variables.

This way is needed because the env function is available only within the default value of a user variable. (See "Environment Variable" section in https://www.packer.io/docs/templates/user-variables.html )

So probably you can modify centos-6.7/template.json like below (add "variables" and "environment_variables" keys):

```
    "variables": {
        "http_proxy": "{{env `http_proxy`}}",
        "https_proxy": "{{env `https_proxy`}}",
        "ftp_proxy": "{{env `ftp_proxy`}}",
        "no_proxy": "{{env `no_proxy`}}"
    },
    "provisioners": [
        {
            "type": "shell",
            "environment_vars": [
                "http_proxy={{user `http_proxy`}}",
                "https_proxy={{user `https_proxy`}}",
                "ftp_proxy={{user `ftp_proxy`}}",
                "no_proxy={{user `no_proxy`}}"
            ],
            "execute_command": "echo 'vagrant'|sudo -S sh '{{.Path}}'",
...
```

I don't have a test environment for proxy settings myself.
Could you try it?
Thanks!

**Comment by SydOps** [comment]
Yes, it is successful to update in building image and generate box file without any errors. Thanks. 

One more question, after the build is done, I got a new file `centos-6-7-x64-virtualbox.box`, I think it is for Vagrant box. 

From the output: 
```
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/packer-virtualbox-iso-1444357077-disk1.vmdk
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/packer-virtualbox-iso-1444357077.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: packer-virtualbox-iso-1444357077-disk1.vmdk
Build 'virtualbox-iso' finished.
```
The image with `.ovf` and .vmdk` are generated as well. But after command finished, these files are disappeared. 

Can I keep them, because I need them for vSphere virtual environment, I need the same image to be used in vagrant and vsphere/vmware.

**Comment by SydOps** [comment]
I see, i just `untar` the `.box` file directly to get `.vmdk` file.

**Comment by hnakamur** [comment]
I am glad that you succeeded in building an image.
Thanks for trying to build an image with a http proxy.
Now I got the tip for building an image with a http proxy thanks to you ;-)

**Comment by SydOps** [comment]
@hnakamur 
my first testing is tested with proxy setting I put in each *.sh script. After i remote the setting in script and only set proxy in template.json, the build is failed. So the problem in fact isn't fixed.
