### ISSUE TITLE
Vmware_Workstation_http_Preseed.cfg not found

### ISSUE THREAD

**Issue by kumarsarath588** [shiguredo/packer-templates#39]
Hi,

I was facing a strange issue when i am trying to create ubuntu 14.04 box file in vmware workstation 12 in linux centos host using packer 8.6.

I wasted around 4 hours trying to spining different boxes using command line and finally realized that its not able to fetch http://<IP>:<Port>/preseed.cfg file while installing OS and finally its timing out.

I understood the issue only after making headless false and working with GUI, and again the same ubuntu 14.04 box is working fine in vmware workstation 12 + windows + packer 8.6.

![Uploading Packer_Vmware_http_preseed_issue.PNG…]()

**Comment by hnakamur** [comment]
Hi @kumarsarath588,
I am sorry to hear that.

I took over the maintenance of this project and I am the only maintainer of this project now.
However I am afraid I don't have a VMware license, so I cannot verify or fix the problem.
Sorry for that.

**Comment by kumarsarath588** [comment]
Hi,

When using "http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg" as preseed/url it gave me error like not able to download http://172.16.128.1:8240/preseed.cfg but from my desktop if i do wget  -qO-http://172.16.128.1:8240/preseed.cfg its able to download the file.

I did some R&D and changed " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>" under "boot_command" to one of my repository where i placed copy of preseed.cfg as preseed-1404.cfg " preseed/url=http://192.168.200.239/artifactory/Software-Repo/preseed-1404.cfg<wait>".

And Boom it works, What do you think is the actual issue.

**Comment by hnakamur** [comment]
Well, I'm afraid I don't know.
Maybe you can see differences between contents of `preseed.cfg` and `preseed-1404.cfg` to determine that is the actual issue.

**Comment by kumarsarath588** [comment]
Both are same, i just did a copy of preseed.cfg to my repo thats it.

Well then i will use this as an alternative solution and i will try to do some more deep dive in it.

Thanks for help

**Comment by hnakamur** [comment]
OK. I am closing this issue now.
Feel free to reopen it when you find out problems.
