### ISSUE TITLE
blank screen after installing a Ubuntu image?

### ISSUE THREAD

**Issue by vemv** [shiguredo/packer-templates#41]
Hey there,

I'm re-using (but not following exactly) your Ubuntu 14.04 Packer setup. Mostly it works fine, but when I launch VirtualBox with one generated image, screen will appear totally black.

I can press ctrl-alt-f1 (or ctrl-alt-f2, ctrl-alt-f3, etc) and get a functional TTY. But I'd expect to get a working terminal since the first moment of launching an image into VirtualBox...

Could it be that there is some wrong/missing setting regarding the screen devices, TTYs, or something similar? Do you recall any similar issue?

Else feel free to close my issue.

Cheers - Victor

**Comment by y3ti** [comment]
@vemv I have resolved this issue by adding:

```
sed -i 's/#GRUB_GFXMODE/GRUB_GFXMODE/' /etc/default/grub
update-grub
```

at the end of `scripts/base.sh`

**Comment by vemv** [comment]
This might be actually useful for one of my current setup (which I keep developing), will have to try.

Anyway my template has diverged a lot from yours, so I'm closing this issue.

Thanks so much!
